version: '3.8'

services:

  mariadb:
    image: mariadb:10.6.14-focal
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    expose:
      - 3306
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    networks:
      - wordpressnetworkstack

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - wordpressnetworkstack

  nginx:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile.alpine
      args:
        ENABLED_MODULES: testcookie-nginx-module ngx_cache_purge modsecurity brotli 
    image: todo1991/nginx_wordpress_alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./logs
        target: /var/log/nginx
      - type: bind
        source: ./nginx/modsec
        target: /etc/nginx/modsec
      - type: volume
        source: certbot-ssl
        target: /etc/letsencrypt
      # mount root document website fix 404, when use php-fpm (fastcgi_pass)
      - type: volume
        source: public_html
        target: /var/www/html
    depends_on:
      - wordpress_instance
    networks:
      - wordpressnetworkstack
  
  wordpress_instance:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile.wp
      args:
        DOMAIN: ${DOMAIN}
    image: todo1991/phpfpm_wordpress_alpine
    container_name: wordpress_instance
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
    # fix REST-API on Site Health Check wordpress
    extra_hosts:
      - ${DOMAIN}:${IPHOST}
    volumes:
      - type: volume
        source: public_html
        target: /var/www/html
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    depends_on:
      - mariadb
      - redis
    networks:
      - wordpressnetworkstack

  certbot:
    image: certbot/certbot
    container_name: certbot
    dns:
      - 8.8.8.8
    volumes:
      - type: volume
        source: certbot-ssl
        target: /etc/letsencrypt
      - type: volume
        source: public_html
        target: /var/www/html
    networks:
      - wordpressnetworkstack

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
    volumes:
      - type: volume
        source: public_html
        target: /var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - wordpressnetworkstack

networks:
  wordpressnetworkstack:
    driver: bridge
    name: wordpressnetworkstack

volumes:
  certbot-ssl:
    external: true
  public_html:
    external: true
  mariadb:
    external: true
