location ~* /(?:uploads|files)/.*\.php$ {
	deny all;
	access_log off;
	log_not_found off;
}

location ~* /wp-content/.*\.php$ {
	deny all;
	access_log off;
	log_not_found off;
}

location = /xmlrpc.php { deny all; }

location ~* /(wp-config\.php) {
	deny all;
}

location = /robots.txt {
	access_log off;
	log_not_found off;
}

# .htaccess, .htpasswd and other .ht* files
location ~ /\.ht {
	deny all;
}
